/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Diana Baez
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    int numera1,numera2;
    int denomina1,denomina2;
    String operador;
    public Pantalla() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTXTnumerador1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        JTXTdenomidador1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        JTXTnumerador2 = new javax.swing.JTextField();
        JTXTdenomidador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        resultNumerador = new javax.swing.JTextField();
        ResultDenominador = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Siete = new javax.swing.JButton();
        Ocho = new javax.swing.JButton();
        Nueve = new javax.swing.JButton();
        Entre = new javax.swing.JButton();
        Cuatro = new javax.swing.JButton();
        Cinco = new javax.swing.JButton();
        Seis = new javax.swing.JButton();
        Multiplica = new javax.swing.JButton();
        Uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));

        JTXTnumerador1.setBackground(new java.awt.Color(204, 255, 255));
        JTXTnumerador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JTXTdenomidador1.setBackground(new java.awt.Color(204, 255, 255));
        JTXTdenomidador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");

        JTXTnumerador2.setBackground(new java.awt.Color(204, 255, 255));
        JTXTnumerador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JTXTdenomidador2.setBackground(new java.awt.Color(204, 255, 255));
        JTXTdenomidador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("=");

        resultNumerador.setBackground(new java.awt.Color(204, 255, 255));
        resultNumerador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ResultDenominador.setBackground(new java.awt.Color(204, 255, 255));
        ResultDenominador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Calcular.setBackground(new java.awt.Color(102, 102, 255));
        Calcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Siete.setText("7");
        Siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SieteActionPerformed(evt);
            }
        });

        Ocho.setText("8");
        Ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OchoActionPerformed(evt);
            }
        });

        Nueve.setText("9");
        Nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NueveActionPerformed(evt);
            }
        });

        Entre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Entre.setText("÷");
        Entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreActionPerformed(evt);
            }
        });

        Cuatro.setText("4");
        Cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuatroActionPerformed(evt);
            }
        });

        Cinco.setText("5");
        Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CincoActionPerformed(evt);
            }
        });

        Seis.setText("6");
        Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeisActionPerformed(evt);
            }
        });

        Multiplica.setText("X");
        Multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicaActionPerformed(evt);
            }
        });

        Uno.setText("1");
        Uno.setToolTipText("");
        Uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoActionPerformed(evt);
            }
        });

        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        mas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        menos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        BotonC.setBackground(new java.awt.Color(255, 0, 0));
        BotonC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonC.setText("C");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(JTXTnumerador1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTXTdenomidador1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(JTXTnumerador2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTXTdenomidador2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Siete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Multiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Entre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(JTXTnumerador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JTXTdenomidador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResultDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JTXTnumerador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTXTdenomidador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(resultNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Entre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Siete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonC))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        // TODO add your handling code here:
        this.JTXTnumerador1.setText("");
        this.JTXTdenomidador1.setText("");
        this.JTXTnumerador2.setText("");
        this.JTXTdenomidador2.setText("");
        this.resultNumerador.setText("");
        this.ResultDenominador.setText("");
    }//GEN-LAST:event_BotonCActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        this.jLabel1.setText("-");
        this.operador="-";
    }//GEN-LAST:event_menosActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        this.jLabel1.setText("+");
        this.operador="+";
       

    }//GEN-LAST:event_masActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("3");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("3");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("3");
        }else {
            this.JTXTdenomidador2.setText("3");
        }
    }//GEN-LAST:event_tresActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("2");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("2");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("2");
        }else {
            this.JTXTdenomidador2.setText("2");
        }
    }//GEN-LAST:event_dosActionPerformed

    private void UnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoActionPerformed
        String ValNumerador1 = this.JTXTnumerador1.getText();
        String ValNumerador2 = this.JTXTnumerador2.getText();
        String ValDenominador1 = this.JTXTdenomidador1.getText();
        String ValDenominador2 = this.JTXTdenomidador2.getText();

        if(ValNumerador1.isEmpty()){
            this.JTXTnumerador1.setText("1");
        }else if(ValDenominador1.isEmpty()){
            this.JTXTdenomidador1.setText("1");
        }else if(ValNumerador2.isEmpty()){
            this.JTXTnumerador2.setText("1");
        }else
        this.JTXTdenomidador2.setText("1");
    }//GEN-LAST:event_UnoActionPerformed

    private void MultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicaActionPerformed
        // TODO add your handling code here:
        this.jLabel1.setText("X");
        this.operador="*";
    }//GEN-LAST:event_MultiplicaActionPerformed

    private void SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeisActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("6");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("6");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("6");
        }else {
            this.JTXTdenomidador2.setText("6");
        }
    }//GEN-LAST:event_SeisActionPerformed

    private void CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("5");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("5");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("5");
        }else {
            this.JTXTdenomidador2.setText("5");
        }
    }//GEN-LAST:event_CincoActionPerformed

    private void CuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatroActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("4");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("4");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("4");
        }else {
            this.JTXTdenomidador2.setText("4");
        }

    }//GEN-LAST:event_CuatroActionPerformed

    private void EntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreActionPerformed
        // TODO add your handling code here:
        this.jLabel1.setText("÷");
        this.operador="/";
    }//GEN-LAST:event_EntreActionPerformed

    private void NueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NueveActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("9");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("9");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("9");
        }else {
            this.JTXTdenomidador2.setText("9");
        }
    }//GEN-LAST:event_NueveActionPerformed

    private void OchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OchoActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("8");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("8");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("8");
        }else {
            this.JTXTdenomidador2.setText("8");
        }
    }//GEN-LAST:event_OchoActionPerformed

    private void SieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SieteActionPerformed
        // TODO add your handling code here:
        String Numerador1Val = this.JTXTnumerador1.getText();
        String Numerador2Val = this.JTXTnumerador2.getText();
        String denominador1 = this.JTXTdenomidador1.getText();
        String denominador2 = this.JTXTdenomidador2.getText();

        if(Numerador1Val.isEmpty()){
            this.JTXTnumerador1.setText("7");
        }else if(denominador1.isEmpty()){
            this.JTXTdenomidador1.setText("7");
        }else if(Numerador2Val.isEmpty()){
            this.JTXTnumerador2.setText("7");
        }else {
            this.JTXTdenomidador2.setText("7");
        }
    }//GEN-LAST:event_SieteActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        int numera1 = Integer.parseInt(this.JTXTnumerador1.getText());
        int denomina1 = Integer.parseInt(this.JTXTdenomidador1.getText());
        this.numera2 = Integer.parseInt(this.JTXTnumerador2.getText());
        this.denomina2 = Integer.parseInt(this.JTXTdenomidador2.getText());
        switch(this.operador){
            case "+":
            Sumar(numera1,denomina1,numera2,denomina2);
            break;
            case "*":
            Multiplica(numera1,denomina1,numera2,denomina2);
            break;
            case "-":
            Resta(numera1,denomina1,numera2,denomina2);
            break;
            case "/":
            Division(numera1,denomina1,numera2,denomina2);
            break;

        }

      
    }//GEN-LAST:event_CalcularActionPerformed
public void Multiplica(int num1, int denom1, int num2, int denom2){
    int numprod, denomprod;
    
    numprod = num1*num2;
   denomprod = denom1*denom2;
    if(denomprod == numprod){
            System.out.println("entero");
            numprod = 1;
            this.resultNumerador.setText(sincero(numprod));
            this.ResultDenominador.setVisible(false);
            this.jSeparator3.setVisible(false);
        }
   this.ResultDenominador.setText(sincero(denomprod));
   this.resultNumerador.setText(sincero(numprod));
   
    
}
    public String sincero(int resultado){
        String retorno = "";
        retorno = Double.toString(resultado);
        if(resultado%1 == 0){
            retorno = retorno.substring(0,retorno.length()-2);
        }
        return retorno;
    }
public void Sumar(int numera1, int denomina1, int numera2,int denomina2){
               
         int denominadorComun = denomina1*denomina2;
        int resultaNumerador = (numera1*denomina2)+(numera2*denomina1);
        
         int gcd = mcd1(resultaNumerador, denominadorComun);
            resultaNumerador /= gcd;
            denominadorComun /= gcd;
            
        
        if(denominadorComun == 1){
            System.out.println("entero");
            this.resultNumerador.setText(sincero(resultaNumerador));
            this.ResultDenominador.setVisible(false);
            this.jSeparator3.setVisible(false);
        }
        this.resultNumerador.setText(sincero(resultaNumerador));
        this.ResultDenominador.setText(sincero(denominadorComun));
        
    }
public void Resta(int numera1, int denomina1, int numera2,int denomina2){
               
        int denominadorComun = denomina1*denomina2; //9
        int resultaNumerador = (numera1*denomina2)-(numera2*denomina1);//3 - 6
        
         int gcd = mcd1(resultaNumerador, denominadorComun);
            resultaNumerador /= gcd;
            denominadorComun /= gcd;
            
        
        if(denominadorComun == 1){
            System.out.println("entero");
            this.resultNumerador.setText(sincero(resultaNumerador));
            this.ResultDenominador.setVisible(false);
            this.jSeparator3.setVisible(false);
        }
        this.resultNumerador.setText(sincero(resultaNumerador));
        this.ResultDenominador.setText(sincero(denominadorComun));
        
    }
public void Division(int numera1, int denomina1, int numera2, int denomina2){
    int numerador = numera1*denomina2;
    int denominador = denomina1*numera2;
     int gcd = mcd1(numerador, denominador);
            numerador /= gcd;
            denominador /= gcd;
         if(denominador == 1){
            System.out.println("entero");
            this.resultNumerador.setText(sincero(numerador));
            this.ResultDenominador.setVisible(false);
            this.jSeparator3.setVisible(false);
        }
    this.resultNumerador.setText(sincero(numerador));
    this.ResultDenominador.setText(sincero(denominador));
}
  private int mcd(int num, int den) {
        int u = Math.abs(num);  
     int v = Math.abs(den);
     if(v == 0){
          return u;
     }
     int r;
     while(v != 0){
          r = u % v;
          u = v;
          v = r;
     }
     return u;
    }
  
  private int mcd1(int a, int b) {
        while (b != 0) {
            int temp = b;
            b = a % b;
            a = temp;
        }
        return a;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonC;
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Cinco;
    private javax.swing.JButton Cuatro;
    private javax.swing.JButton Entre;
    private javax.swing.JTextField JTXTdenomidador1;
    private javax.swing.JTextField JTXTdenomidador2;
    private javax.swing.JTextField JTXTnumerador1;
    private javax.swing.JTextField JTXTnumerador2;
    private javax.swing.JButton Multiplica;
    private javax.swing.JButton Nueve;
    private javax.swing.JButton Ocho;
    private javax.swing.JTextField ResultDenominador;
    private javax.swing.JButton Seis;
    private javax.swing.JButton Siete;
    private javax.swing.JButton Uno;
    private javax.swing.JButton dos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JTextField resultNumerador;
    private javax.swing.JButton tres;
    // End of variables declaration//GEN-END:variables
}
